baseURL: "https://networkx.org/"
languageCode: "en-us"
title: "NetworkX"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["taxonomy"]

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    renderHooks:
      link:
        enableDefault: true

params:
  author:
    name: "NetworkX team"
  description: "Documentation & home page site NetworkX"
  images:
    - /images/networkx_logo.svg
  navbarlogo:
    image: networkx_logo.svg
    text: NetworkX
    link: /
  hero:
    image: networkx_banner.svg
    buttontext: GET STARTED
    buttonlink: /documentation/stable/install.html
  navbar:
    - title: Install
      url: /documentation/stable/install.html
    - title: Tutorial
      url: /documentation/stable/tutorial.html
    - title: Documentation
      url: /documentation/stable/
    - title: Documentation (dev)
      url: /documentation/latest/
    - title: Guides
      url: /nx-guides/

  footer:
    logo: networkx_logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/networkx/
        icon: github
      - link: https://discuss.scientific-python.org
        icon: discourse
      - link: https://discord.com/invite/vur45CbwMz
        icon: discord

